[package]
name = "dirty_memtable"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "dirty_memtable"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
intrusive-collections = "0.9.2"
rustler = "0.22.0"
