[package]
name = "dirty_memtable"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "dirty_memtable"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
archery = "0.4.0"
lazy_static = "1.4.0"
rpds = "0.9.0"
rustler = "0.22.0"
